### ISSUE TITLE
Zenodo links in README are broken

### ISSUE THREAD

**Issue by fmaussion** [rhugonnet/ww_tvol_study#1]
You just need to change them from `[https://doi.org/10.5281/zenodo.4530314]()` to `[https://doi.org/10.5281/zenodo.4530314]([https://doi.org/10.5281/zenodo.4530314)`

But even then, the link is still not working?

**Comment by rhugonnet** [comment]
Thanks Fabien! :)
Wanted to update this morning, but didn't get much time today.
Fixed!
