### ISSUE TITLE
where is the data for processing

### ISSUE THREAD

**Issue by xinluo2018** [rhugonnet/ww_tvol_study#2]
such as : fn_shp = '/home/atom/data/inventory_products/RGI/glims_rgi_region_12/glims_polygons.shp', where is the '/home/atom/data' directory, it is not provided in the repository?

**Comment by rhugonnet** [comment]
Hi Xin,
The data processed within the study is available at [https://doi.org/10.6096/13](https://doi.org/10.6096/13), including the RGI region 12 shapefile, which is specified in the first lines of the README. The raw input data is directly available through the data providers (GLIMS, NASA, etc) referenced in the paper.

**Comment by xinluo2018** [comment]
Got it, thanks for your kind response.

Xin Luo
