### ISSUE TITLE
aster data access

### ISSUE THREAD

**Issue by xinluo2018** [rhugonnet/ww_tvol_study#3]
I don't know which the aster images are used in this study, it not unlikely all the aster images are used due to the glacier area are only covering part of the land and the cloud contamination for the optical images. I noticed the dems/asters/wget_l1a.sh contains a command line: fn_csv=/home/atom/proj/aster_tdem/worldwide/coverage/L1A_retrieval/list_PullDirs_ww_1.csv, are the images id stored in this .csv file? so, does this file is provided in this study? thanks.

**Comment by xinluo2018** [comment]
moreover, in the repo description: Bias-corrected ASTER DEMs (.tif, ~10TB) at 30 m posting, available at TBC. while the link of TBC is unavailable...

**Comment by rhugonnet** [comment]
Hi Xin,
TBC means "To Be Confirmed/Communicated". Please use a search engine before opening an issue: `TBC: to be confirmed: used for showing that something has not been decided yet`

The ASTER DEMs represent several dozens of To which cannot be distributed by us. Those might become available at a later stage through other institutions (e.g. NASA). All the raw data is available directly through NASA's EarthData, and the script to download the data at large scales and process it are available in this repository, and `pymmaster`. All of this is detailed in the README.

**Comment by xinluo2018** [comment]
hi, Rhugonnet, the README mentioned: to download, sort, generate, bias-correct and co-register ASTER DEMs based on ASTER L1A data (~5M CPU hours), could you tell me which script file in the dems/ can directly download the aster data, i am still confused. thanks.

**Comment by xinluo2018** [comment]
hi, Rhugonnet, the dems/create_list_tiles_glacierized.py contains a line: rgi_naming_txt = '/home/atom/proj/aster_tdem/worldwide/rgi_neighb_merged_naming_convention.txt', where is the .txt file, or should create it by oneself?

**Comment by rhugonnet** [comment]
Xin,
There is less than 10 scripts in `dems/aster`, with a description of each script at the first line.
The `wget_l1a` is the downloading script, which you could have found with just a bit of searching on the internet, or by looking at the documentation for bulk download on EarthData Search:
> GNU Wget is a computer program that retrieves content from web servers.
> How To: Use the Download Access Script - EarthData Wiki

The downloading in my scripts depends on what shapefiles you are using to subset your data, here those are the merged RGI shapefiles available at: [https://doi.org/10.6096/13](https://doi.org/10.6096/13). The functioning of the script is described in the general description, code comments. In many places, the Python code itself is pretty straightforward (string manipulation) and describes what is done.

**Please refrain from opening issues which can be resolved by a search engine or outside documentation, I won't be answering those anymore.**

**Comment by xinluo2018** [comment]
thanks for your very useful reply, and sorry to disturb you...
