### ISSUE TITLE
file missing?

### ISSUE THREAD

**Issue by xinluo2018** [rhugonnet/ww_tvol_study#4]
in dems/aster/create_list_tiles_glacierized.py, I could not find the file: '/home/atom/proj/aster_tdem/worldwide/rgi_neighb_merged_naming_convention.txt', could you tell me where or how to create it? thanks.

**Comment by rhugonnet** [comment]
See https://github.com/rhugonnet/ww_tvol_study/issues/3#issuecomment-997368520
