### ISSUE TITLE
pybob version in .yml file should be updated

### ISSUE THREAD

**Issue by bowenbelongstonature** [rhugonnet/ww_tvol_study#5]
`nmad` cannot be imported with pybob==0.24. So, I think the version should >=0.25.

**Comment by rhugonnet** [comment]
The main branch of `pybob` has not changed in 3 years, so it's probably more a branch problem. The `iamdonovan/test_dev` branch is the one to use.
I'll keep this open to remind myself to add a note to the README at a later point.

**Comment by rhugonnet** [comment]
Done in [1c016ef](https://github.com/rhugonnet/ww_tvol_study/commit/1c016efa74c45d06fce06465a048c32f48023dfd).

**Comment by Poleside** [comment]
I found that in here it's scikit-image==0.15.0, while pybob(iamdonovan/test_dev) requires scikit-image>=0.18

**Comment by rhugonnet** [comment]
Good point, the `+git` was also missing to fetch `pybob@iamdonovan/test` via `pip`. All updated and tested locally, the environment builds.
