### ISSUE TITLE
Error when trying to run process_l1a_mmaster.sh

### ISSUE THREAD

**Issue by Poleside** [rhugonnet/ww_tvol_study#7]
Hi, rhugonnet!
With conda env created, I ran into this at the end of the .log file.
I also followed the mmaster doc in another environment, to run WorkFlowASTER.sh, still stopped here

```
For command = ApplyParralaxCor
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    Unknown command in mm3d
|                                                           
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :                                
|                                                            
| Error was detected
|          at line : 1697
|          of file : /home/wqh/Documents/micmac/src/CBinaires/mm3d.cpp
-------------------------------------------------------------
Bye  (press enter)
```

Any idea? Thanks in advance.

**Comment by rhugonnet** [comment]
Hi @Poleside,
Unfortunately I am not a MicMac developer so cannot help you on this error. You need to open an issue in the original repo: https://github.com/luc-girod/MMASTER-workflows but I'm not sure if there is still activity. Double-check that you did all of this: https://mmaster-workflows.readthedocs.io/en/latest/setup.html
Good luck!
