### ISSUE TITLE
Is it okay to use the default kernel?

### ISSUE THREAD

**Issue by Poleside** [rhugonnet/ww_tvol_study#8]
Hello Romain. I'm currently trying to apply this method on a rather small area of the HMA region (region 15) with just one or two tiles and I extended the data to 2023. After the process_stacks_region.py step, I got some results and compared them to the dataset you provided. Although my results look similar to yours in interannual variability, means, etc. However, the overall trend seems a bit different (the dhdt line plot looks like it's vertically compressed). Could this be related to my use of the default kernel, or do you have other thoughts?
Thanks in advance!
:)

**Comment by rhugonnet** [comment]
Hi @Poleside,

Hard to tell from this. Gaussian Processes will always try to fit your elevation data, so there shouldn't be any bias between the results except if the iterative GP routine in `pyddem/fit_tools` is over-filtering somehow before the final fit.
The only differences would be on the edge of your period, or your seasonality, or when there are large temporal data gaps... But if you're using the default kernel, which is indeed the one I used in the study, there shouldn't be any.

One factor that could also influence things a lot is if you are using a different uncertainty during the fit, by default I compute one based on slope/correlation from MicMac.

Hope this helps!

**Comment by Poleside** [comment]
Thank you very much for the answer! I will check the details you mentioned.
:)
